name: Deploy to Cloud Run

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@latest
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Build and push Docker image
      run: |
        gcloud builds submit --config cloudbuild.yml .

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy golang-web-server \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/golang-web-server:latest \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars API_KEY=${{ secrets.API_KEY }},API_SECRET=${{ secrets.API_SECRET }}
