name: Deploy to Cloud Run

on:
  push:
    branches:
      - master

env:
  PROJECT_ID: paper-summarizer-381022
  SERVICE_NAME: paper-summarizer

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions: 
      contents: 'read'
      id-token: 'write'
    
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
      
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0.4.0'
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: github-actions@${{ env.PROJECT_ID }}.iam.gserviceaccount.com
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
      
      - name: Authorize Docker push
        run: gcloud auth configure-docker

      - name: Build Docker image
        run: >-
          docker build 
          -t asia.gcr.io/$PROJECT_ID/$SERVICE_NAME:${{ github.sha }} 
          -f ./docker/Dockerfile 
          --build-arg LINE_MESSAGING_API_CHANNEL_ACCESS_TOKEN=${{ secrets.LINE_MESSAGING_API_CHANNEL_ACCESS_TOKEN }} 
          --build-arg LINE_MESSAGING_API_CHANNEL_SECRET=${{ secrets.LINE_MESSAGING_API_CHANNEL_SECRET }}  
          .

      - name: Push Docker Image
        run: docker push asia.gcr.io/$PROJECT_ID/$SERVICE_NAME:${{ github.sha }}
      
      - name: Deploy to Cloud Run
        run: |-
          gcloud run deploy $SERVICE_NAME \
            --project=$PROJECT_ID \
            --image=asia.gcr.io/$PROJECT_ID/$SERVICE_NAME:${{ github.sha }} \
            --region=asia-northeast1 \
            --service-account=github-actions@${{ env.PROJECT_ID }}.iam.gserviceaccount.com \
            --allow-unauthenticated